---
title: " demo: eumap R package functionalities"
author: "Mohammadreza Sheykhmousa (mohammadreza.sheykhmousa@OpenGeoHub.org) and Tom Hengl (tom.hengl@OpenGeoHub.org)"
date: "Last compiled on: `r format(Sys.time(), '%d %B, %Y')`"
output: 
   rmarkdown::md_document:
    toc: true
    toc_depth: 3
bibliography: ./tex/refs.bib
csl: ./tex/apa.csl  
fig_caption: yes
link-citations: yes
twitter-handle: opengeohub
header-includes:
- \usepackage{caption}
---


```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, comment = '', fig.width = 6, fig.height = 6)
```


```{r, echo=FALSE, warning=FALSE}
hook_output <- knit_hooks$get("output")
knit_hooks$set(output = function(x, options) {
   lines <- options$output.lines
   if (is.null(lines)) {
     return(hook_output(x, options))  # pass to default hook
   }
   x <- unlist(strsplit(x, "\n"))
   more <- "..."
   if (length(lines)==1) {        # first n lines
     if (length(x) > lines) {
       # truncate the output, but add ....
       x <- c(head(x, lines), more)
     }
   } else {
     x <- c(more, x[lines], more)
   }
   # paste these lines together
   x <- paste(c(x, ""), collapse = "\n")
   hook_output(x, options)
 })
```


## Loading required libraries:
```{r, message=FALSE, warning=FALSE}

library("eumap")

# core libraries###
library(mlr3verse)
library(mlr3tuning)
library(mlr3spatiotempcv)
library(future)
library(checkmate)

# graphical libraries###
library(likert)
library(cvms)
library(broom)    
library(tibble)   
library(ggimage)   
library(rsvg)   
library(grid)
library(hexbin)
library(BBmisc)
library(lattice)
library(gridExtra)
library(latticeExtra)

# mathematical and geospatial libraries###
library(sp)
library(caret)
library(MLmetrics)
library(yardstick)
library(ppcor)
library(progressr)
library(scales)
```


```{r}
# file <- 'https://drive.google.com/file/d/1Y3ao-SkWjhjaBQiXvgDq03ecYFE0WOFH/view?usp=sharing' 
# #you can download the file using this link.
# download.file(file, destfile)
# in.data = 'C:/Enter/gitrepo/eumap/sample.RData'
load('C://Users/mohammad-reza/Downloads/sample.RData')
```

## pre-processing
```{r}
sample$clc3_red <- as.factor(sample$clc3_red)
sample$X <- NULL
sample$confidence <- NULL
sample$ecoregion_id <- NULL
sample$gsw_occurrence_1984_2019 <- NULL

```

## `train_spm`

```{r ,results='hide', warning=FALSE}
target.variable = "clc3_red"
df.tr = 'sample'
tr = train_spm(df.tr = data.frame(sample), target.variable = target.variable, folds = 2, n_evals = 1)
train_model = tr[[1]]
Vim = tr[[2]]
tr[[3]]
response = tr[[4]]
```

```{r, echo=FALSE}
vlp = tr[[5]]
```

## `predict_spm`

```{r ,output.lines= -(3:300)}
predict.variable = predict_spm(train_model, newdata = data.frame(sample))

```

```{r ,output.lines= -(3:300)}

pred.v = predict.variable[1]

```

```{r ,results='hide', echo=FALSE}

valu.imp = predict.variable[[2]]

```

## `plot_spm` 

### variable importance
```{r, ,results='hide'}

plot_spm( Vim = Vim, gtype = "var.imp")

```

### confusion matrix

```{r}
response = tr[[4]]
target.variable = "clc3_red"
df.tr = data.frame(sample)
p = plot_spm(x = df.tr[,target.variable], y = pred.v[[1]], gtype = 'cm') 
p
```

