utils::globalVariables(c('df.tr'
,'target'
,'pred.v'
,'valu.imp'
,'var.imp'
,'title'
,'xscale.components.logpower'
,'yscale.components.logpower'
,'yscale.components.log10ticks'
,'xscale.components.log'
,'yscale.components.log'
,'xscale.components.subticks'
,'yscale.components.subticks'
,'target.variable'
,'vlp'
,'grid.arrange'
,'vlp'
,'ParamSet'
,'ParamInt'
,'ParamDbl'
,'ParamFct'
,'%>>%'
,'normalize'
,'AutoTuner'
,'TaskClassif'
,'TaskClassifS'
,'TaskRegr'
,'TaskRegrST'
,'alpha'
,'lattice'
,'as_data_backend'
,'availableCores'
,'ccc'
,'union'
,'hexbinplot'
,'lrn'
,'msr'
,'TaskClassifST'
,'gunion'
,'scales'
,'progress'
,'latticeExtra'
,'geom_tile'
, 'scale_fill_gradient2'
, 'geom_text'
, 'aes'
, 'theme_light'
, 'theme'
, 'element_blank'
, 'Prediction'
, 'Reference'
, 'Freq'
, 'scale_x_discrete'
, 'ref_freq'
,'confusionMatrix'
, 'reverse.levels'
, 'ggplot'
, 'panel.abline'
,'panel.hexbinplot'
,'panel.xyplot'
,'pcor'
,'po'
,'rmse'
,'rsmp'
,'tnr'
,'trm'
,'term'
,'xyplot'))
