name: Python sphinx

on:
  push:
    paths:
      - 'skmap/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'setup.py'
      - 'pyproject.toml'

jobs:
  doctest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libproj-dev libgeos-dev gdal-bin libgdal-dev pandoc doxygen build-essential
          gdal-config --version
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Run doctests
        run: |
          gdal-config --version
          uv pip install .[full,dev,docs]
          doxygen
          . .venv/bin/activate
          sphinx-build -M doctest docs/ _build/
      - name: Build docs
        run: |
          . .venv/bin/activate
          sphinx-build docs/ _build/
          rm -rf build/*.linux-*
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
